# Chat Svelte App

This Svelte application demonstrates how to use the Google Generative AI API to create a chat interface. The application allows users to input questions and receive responses generated by the AI model.

## Prerequisites

- Node.js and npm (or yarn) installed
- A Google Cloud Platform project with the Generative AI API enabled
- A service account with the necessary permissions
- An API key for the Google Generative AI API

## Installation



1. **Install dependencies:**

    ```bash
    npm install @google/generative-ai
    ```

2. **Configure API Key:**

    Replace the placeholder API key with your actual API key:
    ```javascript
    let apiKey = "YOUR_ACTUAL_API_KEY";
    ```

## Usage

1. **Run the Application:**

    ```bash
    npm run dev
    ```

2. **Open the Application:**

    Open your browser and navigate to `http://localhost:3000` to view the application.

## Script Details

- **GoogleGenerativeAI:** The application uses the `GoogleGenerativeAI` class to interact with the Google Generative AI API.
- **Model Configuration:** The model is configured with specific parameters such as temperature, topP, topK, maxOutputTokens, and responseMimeType.
- **Chat Functionality:** Users can input questions, and the AI model generates responses based on the chat history.


## Dependencies

- `@google/generative-ai`
- `svelte`

## Screenshot

![Chat Interface](https://github.com/Rivalcoder/Gen-Ai-Training/blob/main/Chat-Svelte/Screenshot%202024-12-21%20141746.png)

